spring:
  application:
    name: zipkin-server
  sleuth:
    enabled: false
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
#  datasource:
#    username: root
#    url: jdbc:mysql://localhost:3306/spring-cloud-zipkin?useUnicode=true&characterEncoding=utf8&useSSL=false
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9411
zipkin:
  storage: #表示zipkin数据存储方式是elasticsearch
    StorageComponent: elasticsearch
    type: elasticsearch
  elasticsearch:
    cluster: elasticsearch #集群
    max-requests: 30 #最大请求时间
    index: zipkin*
    index-shards: 3
    index-replicas: 1
    hosts: http://localhost:9200 #elasticsearch管理地址


